### PR TITLE
[1398] Sort embargo vocab words by embargo position in student submission view

### LINKED ISSUE #1398: BUG - Reordering Default Embargoes does not display in submission view
Reordering of global Default Embargoes in settings does not show up in student Submission View.  Unlike custom embargoes, the global (system default) Embargo types can be reordered in the Settings, but they will not appear in the new order in new student submissions.

### PR DESCRIPTION
**Pull request by jsavell**
Resolves #1398

### CODE REVIEW

**Comment by jsavell** [comment]
I corrected the embargo order for the view when the student is creating a new submission but missed this other view. Updating it now.

**Comment by jsavell** [comment]
@smutniak 

All three student submission views listing embargoes are now sorted. I think that's all of them...

**Comment by jsavell** [comment]
Can you test with a fresh build of this branch without any branch switching?

**Comment by smutniak** [comment]
It works in isolation but I retested using the 1399 fix to reorder and then test this branch and it still fails.  I'll merge this PR but revisit testing of the staging branch where both branches are present.

**Comment by smutniak** [comment]
@jsavell I've retested this on 4.0.x_may2020_staging and see that it still fails to display embargoes in the students submission page.  It appears that removing 'is-embargo="isEmbargo"' from line 46 of webapp/app/views/submission/submission.html results in the embargoes being displayed. I didn't test further to see if they sort without that attribute.  Can you please revisit?

**Comment by jsavell** [comment]
Are you positive your browser's html cache is cleared?

I just checked out the staging branch and was able to view and select embargoes with a student submission without any issue. I could also see the embargoes properly from the student submission review page.

I tested with Chrome and Firefox.

I also tested with untouched system default embargoes and with customized and sorted embargoes.

**Pull request merged**
