### PR TITLE
Issue 1714: Fix customize filters modal drag and drop behavior

### PR DESCRIPTION
**Pull request by wwelling**
The angular filter in the template was causing the index being offset. Moving the filter into the controller before the template render resolved the issue. Additional refactoring and formatting.

### CODE REVIEW

**Review by cstarcher — COMMENTED** [review]
Filter are arranging correctly, but they do not save when clicking the Save button.

**Comment by wwelling** [comment]
@cstarcher thanks for the review. Will resolve ASAP.

**Comment by wwelling** [comment]
@cstarcher I see. The save actually does persist but reverts changes on response to request. You should see the intended custom filters and order on page refresh. Fixing the response handling now.

**Comment by wwelling** [comment]
@cstarcher, I believe I have the issue resolved now. Please also test customize view along with customize filters. Both should work with and without page refresh.

**Pull request merged**
